### PR TITLE
trafficlight_Penny_Brunocheckthisout

### PR DESCRIPTION
**Pull request by Pennylele**
Hi Bruno,

Thank you for grading the homework! I messed up with my git a little bit...I have been trying to remove my commits. Actually I have removed some, but I was having a hard time deleting the last one "trafficlight_Penny"...So just check out the trafficlight_Penny_Brunocheckthisout(517516f), which looks more clean! 

If you know how to remove commit  3424606, could you please let me know? Thank you!!

Penny

### CODE REVIEW

**Comment by nsuitter** [comment]
Hi Penny,

Removing commits isn't really recommended, unless you are very certain you want to remove them. It's better to remove content, commit that, and push--that way you keep a history of your entire project. We'll be sure and grade the content in 517516f 

Thanks!
Nathan

**Comment by Pennylele** [comment]
Thank you Nathan! I made another “cleanup” commit, so everything is up-to-date and my local matches my remote again! 

Deleting my commits was because I thought too many commits would confuse you and bruno when grading the homework…but I was also thinking if there’s a way to select a commit to pull request instead of pull request for all commits you have made…

Thank you for clearing things up!

Best,
Penny

**Comment by nsuitter** [comment]
:+1:

**Comment by nsuitter** [comment]
@Pennylele it looks like you haven't submitted an assignment on Moodle yet. Can you please do that so we can give you a grade? Thanks

**Comment by Pennylele** [comment]
@nsuitter sorry that I didn't notice the submit button on the bottom. Now it's there. Thanks!

Penny

**Comment by brossi1** [comment]
Hi Penny, thanks, and I'm sorry but I don't understand why you committed and pushed changes in the fashion blog files too - am I missing something?

**Comment by Pennylele** [comment]
@brossi1 because I think maybe my local and remote were not the same the last time I submitted fashion blog homework. That's why this time git wanted me to solve the difference before committing the new homework...Can you grade on commit 517516f? I'm not sure how the grade works? 

Sorry that I made it complicated...I saw that my pull request contains merge conflicts, I can check see what I can do about it!

**Comment by Pennylele** [comment]
@brossi1 Hi Bruno! If I don't have write access to the repo, I think maybe I can't solve the merge conflicts... Maybe you can just merge commit 517516f rather than the other ones? Please let me know what I can do about it! Thank you!!

Penny

**Comment by Pennylele** [comment]
Bruno! I think I recalled what I did the last time. I changed the .css code on github instead of changing it on my local and then pushing it...(It is a really bad practice)...Then probably I changed my local .css files later too(I'm not so sure), so this time, git asks me to push the changes before committing my traffic light homework files...Hope this helps! I'm really sorry for confusing you and thank you for asking me about it!

Penny

**Comment by nsuitter** [comment]
@Pennylele merging this in a separate commit. Nice job on the homework though!

-indentation is perfect
-love the comments in the html file--things like that really help code readability
-js works great
:+1:

**Pull request merged**
