### PR TITLE
adding cookies_recipe.html

### PR DESCRIPTION
**Pull request by linncch**

### CODE REVIEW

**Comment by brossi1** [comment]
Hi Linn, glad it worked! As I had commented before, the page looks good in the browser, the image is the right size and the hyperlink works (linking to a different website than the one in the instructions, but that's okay).
There is some indentation but some of the elements are not indented. Also, the meta and style elements would normally be nested inside the head element (like the body tag and the ol with recipe instructions).

**Comment by linncch** [comment]
Thanks Bruno. I made the changes you suggested to the homework file and the one just submitted should be okay : )? Have a good night!

---

发件人: Bruno notifications@github.com
发送时间: 2015年2月25日 23:01
收件人: miis-l10n/website-l10n_homework
抄送: Hu, Chenchen
主题: Re: [website-l10n_homework] adding cookies_recipe.html (#28)

Hi Linn, glad it worked! As I had commented before, the page looks good in the browser, the image is the right size and the hyperlink works (linking to a different website than the one in the instructions, but that's okay).
There is some indentation but some of the elements are not indented. Also, the meta and style elements would normally be nested inside the head element (like the body tag and the ol with recipe instructions).

**Comment by brossi1** [comment]
Hi Linn, I accepted the new HTML file but the grading is still based in the first submission, as it wouldn't be fair to other groups to give you a grade after I gave you the feedback. Hope you understand.

**Comment by linncch** [comment]
Sure! :)

On Feb 25, 2015, at 11:12 PM, Bruno <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Linn, I accepted the new HTML file but the grading is still based in the first submission, as it wouldn't be fair to other groups to give you a grade after I gave you the feedback. Hope you understand.

##

**Pull request merged**
