### PR TITLE
CSS Styling Assignment

### PR DESCRIPTION
**Pull request by zoeyingdi**
Please find my html and css files for the Fashion Style Assignment. Thank you.

### CODE REVIEW

**Comment by brossi1** [comment]
Hi Yingdi, nice work! However, your CSS is not consistently indented. Most of the hyperlinks in your page are blue and not gray or red (only exception is the h1). Other than that, your page looks really good! 

http://htmlpreview.github.io/?https://github.com/zoeyingdi/website-l10n_homework/blob/master/Almost_There/Styling_Yingdi%20Qi/Fashion.html

**Comment by brossi1** [comment]
Duncan's submission has the same issues with CSS indentation and links showing up as blue instead of red.

**Comment by zoeyingdi** [comment]
Thank you so much, Bruno :-) Now I know what went wrong so the links showing up as wrong color. As for CSS indentation, what might be the rules? If you have any resources, please let me know. 

Thank you and I am sending my best wishes. Hope all your kindness come back to you in a magical way :-)

My best,
Yingdi

**Comment by brossi1** [comment]
Hi Yingdi, some things to consider:
- make sure that the elements are all aligned (some elements had one tab before, some had two...) EX: lines 4, 6 and 11 of your CSS should be aligned on the left

other things that are not a problem in your code, but may help with consistency in indentation:
- if you use a space between the selector and the curly brackets, use in all of them
- if you are leaving a line of space between each selector, also, be consistent

Code can be confusing sometimes - a single slip like forgetting a comma could make you waste hours debugging, so try to make your code consistent and easy to read, in order to make your job easier (and ours too!)... it's easier to spot issues when your code is neat :)

**Comment by zoeyingdi** [comment]
Thank you so much for bringing this into my attention, Bruno. The bullet points are very helpful. 
You'll find neater code in my following assignments. :)

**Pull request merged**
