### PR TITLE
Adding Traffic Light homework

### PR DESCRIPTION
**Pull request by rzubiate**
This is my html and css files. I'm having trouble adding my js file. It says that there is no such file or directory

### CODE REVIEW

**Comment by nsuitter** [comment]
Do you have a file called main.js in the website-l10n_homework/Almost_There/Rachel-TrafficLight/ folder on your computer?

**Comment by rzubiate** [comment]
I do. I've been working with Bruno too and we tried removing main.js and
then adding it back through git and it's not working still. I also tried
recreating the file but I keep getting the same message.

**Comment by nsuitter** [comment]
@rzubiate That's very strange indeed. If you're totally stuck, you can zip up your git repo (the website-l10n_homework folder on you computer) and send it to me in an email, along with your main.js so I can take a look to see what's going on.

**Comment by nsuitter** [comment]
I downloaded your js file and tried it out locally and it works great. Nice job on your indentation too--it's so consistent!
:+1:

**Pull request merged**
