### PR TITLE
Adding Cookies HW

### PR DESCRIPTION
**Pull request by ncrhodes**
Our group has decided to submit my version of the HTML file since I got a bit fancy with it and was able to show some different features (list styles). Nonetheless, I hadn't seen the "trademark" in the cookies PNG, nor did I realize that there was a problem with my apostrophe.

### CODE REVIEW

**Comment by ncrhodes** [comment]
I added a blank file named octocat.txt to make sure that I didn't mess up my ability to push things to the homework repository. Our group set up another group repository, but in messing up with the "push simple" and "push matching" settings, I'm no longe able to push to it.

**Comment by nsuitter** [comment]
@ncrhodes the push simple vs. push matching should be relevant only if you are on a different branch. When you run `git status` can you give let me know what you see instead of 'on branch <branch>'

**Comment by ncrhodes** [comment]
I'm still able to push to your repository, but can no longer push to our
group's because when I messed with the simple vs matching setting (upon a
git prompt), it started asking me to specify where I was pushing it. I
 renamed it "practice" in git config but when I try to push there I can't.
Maybe we can go over this during the break? It's not critical whatsoever,
but our group wants to have its own repository for reviewing HW assignments
so that we don't have to get together (some of us live an hour's drive from
campus) and can use github as much as possible.

nathan@nathan-Inspiron-3531:~$ cd miis

nathan@nathan-Inspiron-3531:~/miis$ git status

En la rama master

Cambios para hacer commit:

(use «git reset HEAD <archivo>...«para eliminar stage)

 new file: HTML site recreation/Nathan's_cookies.html

new file: HTML site recreation/cookierecipe_isabelle.html

new file: HTML site recreation/index.html

new file: Pictures of bicycles/HistoryofBicycleMarketing5.png

new file: Pictures of bicycles/HistoryofBicycleMarketing7.png

new file: Pictures of bicycles/Rhodes_historia_mercadeo_bici.png

new file: Pictures of bicycles/Rhodes_historia_mercadeo_bicicleta.png

new file: README.md

Cambios no preparados para el commit:

(use «git add/rm <archivo>...» para actualizar lo que se ejecutará)

(use «git checkout -- <archivo>...« para descartar cambios en le directorio
de trabajo)

 deleted: Group Practice Repo/HTML site recreation/Nathan's_cookies.html

deleted: Group Practice Repo/HTML site
recreation/cookierecipe_isabelle.html

deleted: Group Practice Repo/HTML site recreation/index.html

deleted: Group Practice Repo/Pictures of
bicycles/HistoryofBicycleMarketing5.png

deleted: Group Practice Repo/Pictures of
bicycles/HistoryofBicycleMarketing7.png

deleted: Group Practice Repo/Pictures of
bicycles/Rhodes_historia_mercadeo_bici.png

deleted: Group Practice Repo/Pictures of
bicycles/Rhodes_historia_mercadeo_bicicleta.png

deleted: Group Practice Repo/README.md

deleted: Group Practice Repo/push.default

Archivos sin seguimiento:

(use «git add <archivo>...» para incluir lo que se ha de ejecutar)

 Group Practice Repo/Get_a_name/

my_git_repo/

website-l10n/

website-l10n_homework/

nathan@nathan-Inspiron-3531:~/miis$ git commit -m "changed folder names on
group repo"

[master b7d5e4c] changed folder names on group repo

8 files changed, 281 insertions(+)

create mode 100644 HTML site recreation/Nathan's_cookies.html

create mode 100644 HTML site recreation/cookierecipe_isabelle.html

create mode 100644 HTML site recreation/index.html

create mode 100644 Pictures of bicycles/HistoryofBicycleMarketing5.png

create mode 100644 Pictures of bicycles/HistoryofBicycleMarketing7.png

create mode 100644 Pictures of bicycles/Rhodes_historia_mercadeo_bici.png

create mode 100644 Pictures of
bicycles/Rhodes_historia_mercadeo_bicicleta.png

create mode 100644 README.md

nathan@nathan-Inspiron-3531:~/miis$ git push

fatal: No configured push destination.

Either specify the URL from the command-line or configure a remote
repository using

 git remote add <name> <url>

and then push using the remote name

 git push <name>

nathan@nathan-Inspiron-3531:~/miis$ git push origin master

fatal: 'origin' does not appear to be a git repository

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

nathan@nathan-Inspiron-3531:~/miis$ git push practice master

Username for 'https://github.com': ncrhodes

Password for 'https://ncrhodes@github.com':

To https://github.com/ncrhodes/Get_a_name.git

! [rejected] master -> master (non-fast-forward)

error: failed to push some refs to '
https://github.com/ncrhodes/Get_a_name.git'

consejo: Updates were rejected because the tip of your current branch is
behind

consejo: its remote counterpart. Integrate the remote changes (e.g.

consejo: 'git pull ...') before pushing again.

consejo: See the 'Note about fast-forwards' in 'git push --help' for
details.

nathan@nathan-Inspiron-3531:~/miis$ git pull practice

You asked to pull from the remote 'practice', but did not specify

a branch. Because this is not the default configured remote

for your current branch, you must specify a branch on the command line.

nathan@nathan-Inspiron-3531:~/miis$ git push
https://github.com/ncrhodes/Get_a_name.git

fatal: The current branch master has no upstream branch.

To push the current branch and set the remote as upstream, use

 git push --set-upstream https://github.com/ncrhodes/Get_a_name.git master

 nathan@nathan-Inspiron-3531:~/miis$

2015-02-23 9:24 GMT-08:00 nsuitter notifications@github.com:

**Comment by brossi1** [comment]
Hi Nathan, nice work, and very funny too. Page works on browser, image is the right size and hyperlink works. However, I merged and graded your group homework based on Isabelle's version, which had slightly better indentation.

**Pull request closed without merging**
