### PR TITLE
adding cookies recipe homework

### PR DESCRIPTION
**Pull request by linncch**

### CODE REVIEW

**Comment by brossi1** [comment]
Hi Linn, I see that you included the 99_bottles.sh file in this submission too - was it by accident? I will wait for your reply before merging.

About your HTML submission: Good work, your image is the right size and the hyperlink is working. The page displays well in the browser. However, your code is missing the "head" element. Also, you could indent the "head" and "body" elements for better readability of the code.

**Comment by linncch** [comment]
?Hi Bruno,

I think it's because Ben submitted the 99_bottles homework and I have a different file in my homework folder. Is there any way that I can submit only the html homework? Thanks!

Linn

---

发件人: Bruno notifications@github.com
发送时间: 2015年2月24日 10:47
收件人: miis-l10n/website-l10n_homework
抄送: Hu, Chenchen
主题: Re: [website-l10n_homework] adding cookies recipe homework (#26)

Hi Linn, I see that you included the 99_bottles.sh file in this submission too - was it by accident? I will wait for your reply before merging.

About your HTML submission: Good work, your image is the right size and the hyperlink is working. The page displays well in the browser. However, your code is missing the "head" element. Also, you could indent the "head" and "body" elements for better readability of the code.

**Comment by brossi1** [comment]
Yes, do the following:

1) remove your 99_bottles.sh file from the folder
2) $ git status (It will tell you that this file has been removed)
3) $ git checkout -- blue_sharks/99_bottles/99_bottles.sh (not sure that is the right path, just double check where you are in Terminal)
4) $ git push

**Comment by linncch** [comment]
I deleted all files except the cookie_recipe.html in the folder and ran git checkout website_l10n_homework/blue_sharks/99_bottles/99_bottles.sh? but it didn't work. Then I ran git add -A which seemed to have staged the changes. But I couldn't commit the changes when I ran git commit. Here's the message I got when I run git status:

chenchens-mbp:website-l10n_homework chenchenhu$ git status

On branch master

Your branch and 'origin/master' have diverged,

and have 2 and 1 different commit each, respectively.

  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.

  (use "git commit" to conclude merge)

nothing to commit, working directory clean

?

---

发件人: Bruno notifications@github.com
发送时间: 2015年2月24日 11:12
收件人: miis-l10n/website-l10n_homework
抄送: Hu, Chenchen
主题: Re: [website-l10n_homework] adding cookies recipe homework (#26)

Yes, do the following:

1) remove your 99_bottles.sh file from the folder
2) $ git status (It will tell you that this file has been removed)
3) $ git checkout -- blue_sharks/99_bottles/99_bottles.sh (not sure that is the right path, just double check where you are in Terminal)
4) $ git push

**Comment by brossi1** [comment]
Hi Linn, you don't have to add anything since you are checking out (removing), and then you don't have to commit that. So just run git push after git checkout.

**Comment by linncch** [comment]
?

I tried running git checkout a few times and got this error every time. I checked that the path is right.

chenchens-mbp:website-l10n_homework chenchenhu$ git checkout /Users/chenchenhu/miis/website-l10n_homework/blue_sharks/99_bottles/99_bottles.sh

error: pathspec '/Users/chenchenhu/miis/website-l10n_homework/blue_sharks/99_bottles/99_bottles.sh' did not match any file(s) known to git.

Seems it's gone a bit messy... Will you be in the portfolio class this afternoon? Can I meet with you before class or during the break? I think I need some help to sort things out here...Thanks.
?

---

发件人: Bruno notifications@github.com
发送时间: 2015年2月24日 12:18
收件人: miis-l10n/website-l10n_homework
抄送: Hu, Chenchen
主题: Re: [website-l10n_homework] adding cookies recipe homework (#26)

Hi Linn, you don't have to add anything since you are checking out (removing), and then you don't have to commit that. So just run git push after git checkout.

**Comment by brossi1** [comment]
Yes, I will be there. See you then!

**Comment by brossi1** [comment]
Hi Linn, this is what Nathan suggests to do:

ATTENTION: Before doing anything else, save your HTML file in your Desktop or another folder, because the next steps will delete it from your local repository

move into the homework folder
git remote update (gets all the data you need)
git reset hard origin/master (puts your local and your fork in the same state)
git status
(remove any files that git lists as new or changed)
(remove the blue_sharks/99_bottles/99_bottles.sh file manually)
(add the HTML file in the folder again)
git add --all
git commit -m "removing extra 99_bottles.sh"
git push origin master

**Comment by linncch** [comment]
?Many thanks Bruno! I think it worked and I created a new pull request. Let me know if it's right this time...

---

发件人: Bruno notifications@github.com
发送时间: 2015年2月25日 22:34
收件人: miis-l10n/website-l10n_homework
抄送: Hu, Chenchen
主题: Re: [website-l10n_homework] adding cookies recipe homework (#26)

Hi Linn, this is what Nathan suggests to do:

Before doing anything else, save your HTML file in your Desktop or another folder, because the next steps will delete it from your local repository <<<

move into the homework folder
git remote update (gets all the data you need)
git reset hard origin/master (puts your local and your fork in the same state)
git status
(remove any files that git lists as new or changed)
(remove the blue_sharks/99_bottles/99_bottles.sh file manually)
(add the HTML file in the folder again)
git add --all
git commit -m "removing extra 99_bottles.sh"
git push origin master

**Pull request closed without merging**
